name: Execute Test Scripts

on:
  repository_dispatch:
    types: [execute-tests]

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      BRANCH_NAME: ${{ github.event.client_payload.branch }}
      TCP_ORDER: ${{ github.event.client_payload.tcp_order }}
      PRN: ${{ github.event.client_payload.pr_number }}
    steps:
      - name: Checkout repository on dispatched branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 1

      - name: Set up Python with caching
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies (cached)
        run: |
          python -m pip install --upgrade pip --quiet
          pip install -r requirements.txt --quiet

      - name: Execute test scripts and record results
        id: exec
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          PRN: ${{ env.PRN }}
        run: python .github/workflows/execute.py

      - name: Commit fault matrix
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Stage fault matrix JSON files only
          git add test/fault-matrices/*.json
          
          if git diff --cached --quiet; then
            echo "No fault matrix changes to commit."
          else
            # Commit fault matrix
            git commit -m "Execute: new fault matrix" --quiet
            git push origin ${{ env.BRANCH_NAME }} --quiet
          fi

      - name: Reprioritize with reinforcement learning for next cycle
        if: ${{ steps.exec.outputs.all_passed != 'true' }}
        run: |
          echo "Failures detected; reprioritizing for next execution cycle..."
          python .github/workflows/prioritize.py

      - name: Commit reprioritized tcp.json for next cycle
        if: ${{ steps.exec.outputs.all_passed != 'true' }}
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add test/tcp.json
          
          if ! git diff --cached --quiet; then
            git commit -m "[skip-execute] Reprioritize: updated tcp.json for next cycle" --quiet
            git push origin ${{ env.BRANCH_NAME }} --quiet
          else
            echo "No changes to tcp.json."
          fi

      - name: Approve PR if all tests passed
        if: ${{ env.PRN != '' && steps.exec.outputs.all_passed == 'true' }}
        run: |
          gh pr review ${{ env.PRN }} --approve --body "✅ All test cases passed in this execution."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
