name: Prioritise Test Case Order

on:
  repository_dispatch:
    types: [prioritise-cases]

jobs:
  prioritise-order:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH_NAME: ${{ github.event.client_payload.branch }}
    steps:
      - name: Checkout repository on dispatched branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prioritise test cases
        id: tcp
        run: python .github/workflows/prioritise.py
      - name: Find PR Number for branch
        id: prn
        run: |
          BRANCH="${{ env.BRANCH_NAME }}"
          PR_NUMBER=$(gh pr list --state open --json headRefName,number | jq -r ".[] | select(.headRefName==\"$BRANCH\") | .number")
          if [ -z "$PR_NUMBER" ]; then
            echo "prn=" >> $GITHUB_OUTPUT
          else
            echo "prn=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post TCP order as PR comment
        if: ${{ steps.prn.outputs.prn != '' }}
        run: |
          echo "${{ steps.tcp.outputs.TCP_ORDER }}"
          TCP_ORDER=$(echo '${{ steps.tcp.outputs.TCP_ORDER }}' | jq -r '. | join("\n")')
          COMMENT="### Latest Test Case Prioritization Order\n$TCP_ORDER"
          gh pr comment ${{ steps.prn.outputs.prn }} --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch execute-tests workflow
        run: |
          PAYLOAD=$(jq -c \
            --arg branch "${{ env.BRANCH_NAME }}" \
            --argjson tcp_order '${{ steps.tcp.outputs.TCP_ORDER }}' \
            --arg pr_number "${{ steps.prn.outputs.prn }}" \
            '{event_type: "execute-tests", client_payload: {branch: $branch, tcp_order: $tcp_order, pr_number: $pr_number}}')
          echo "$PAYLOAD"
          echo "$PAYLOAD" | gh api repos/megat-z/Random-Math-Test/dispatches --method POST --input -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
